USE [COOP_PAM]
GO

/****** Object:  Table [dbo].[ASSORTMENTS]    Script Date: 3/5/2021 6:40:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ASSORTMENTS](
	[ASSRTMNT_ID] [int] IDENTITY(1,1) NOT NULL,
	[ASSRTMNT_NAME] [nchar](100) NOT NULL,
	[ASSRTMNT_ACTIVE_FROM] [datetime] NOT NULL,
	[ASSRTMNT_ACTIVE_TO] [datetime] NULL,
 CONSTRAINT [PK_ASSORTMENTS] PRIMARY KEY CLUSTERED 
(
	[ASSRTMNT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


