USE [COOP_PAM]
GO

/****** Object:  Table [dbo].[ASSORTMENT_PRODUCTS]    Script Date: 3/5/2021 6:36:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ASSORTMENT_PRODUCTS](
	[PRODUCT_ID] [int] NOT NULL,
	[ASSRTMNT_ID] [int] NOT NULL,
 CONSTRAINT [PK_ASSORTMENT_PRODUCTS] PRIMARY KEY CLUSTERED 
(
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ASSORTMENT_PRODUCTS]  WITH CHECK ADD  CONSTRAINT [FK_ASSORTMENT_PRODUCTS_ASSORTMENT] FOREIGN KEY([ASSRTMNT_ID])
REFERENCES [dbo].[ASSORTMENTS] ([ASSRTMNT_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ASSORTMENT_PRODUCTS] CHECK CONSTRAINT [FK_ASSORTMENT_PRODUCTS_ASSORTMENT]
GO

ALTER TABLE [dbo].[ASSORTMENT_PRODUCTS]  WITH CHECK ADD  CONSTRAINT [FK_ASSORTMENT_PRODUCTS_PRODUCT] FOREIGN KEY([PRODUCT_ID])
REFERENCES [dbo].[PRODUCTS] ([PRODUCT_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ASSORTMENT_PRODUCTS] CHECK CONSTRAINT [FK_ASSORTMENT_PRODUCTS_PRODUCT]
GO


